server:
  port: 8482
  servlet:
    encoding:
      #SpingBoot内置了CharacterEncodingFilter编码过滤，默认为ISO-8859-1
      enabled: true
      #设置CharacterEncodingFilter编码格式为UTF-8
      charset: utf-8
      force: true
    context-path: /blog

  ssl:
    key-store: classpath:blog.yiqu.love.jks
    key-store-type: JKS
    key-alias: blog.yiqu.love
    key-store-password: v21d6hcdux
    key-password: v21d6hcdux

spring:
  profiles:
    #启用database.yml配置
    active: database

  mvc:
    pathmatch:
      #swagger配置
      matching-strategy: ant_path_matcher

  mail:
      host: mail.163.com
      username: yiqumail@163.com
      password: LSL010325ok
      default-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: blog.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt
yiqu:
  jwt:
    # 部署上线务必修改此配置，以保证token的安全性
    secret: YIQU!@#$%^&*767299026
    expire: 172800
    header: token

#shiro包中redis-jedis连接主机配置
shiro:
  redis:
    redisHost: 172.17.0.3:6379
    password: LSL!20010418